server:
  port: 8882

spring:
  application:
    name: es-test
  #Native Elasticsearch binary协议，也就是Transport client配置项，最终要被废弃。
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch # 集群名
#      cluster-nodes: 127.0.0.1:9200 # 集群节点
#      repositories:
#        enabled: true
  #HTTP协议，支持的客户端有Jest client和Rest client
  elasticsearch:
#    jest:
#      uris: http://localhost:9200
    rest:
      uris: http://localhost:9200

logging:
  config: classpath:logback-spring.xml # 自定义logback配置，增加文件滚动式配置
  log-home: /es-log/

